name: charts/octane

on:
  push:
    paths:
      # - charts/octane/**
      - .github/workflows/charts-octane-ci.yml
      # - tests/**

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        kubernetes:
          # - '1.20.10'
          # - '1.21.4'
          - '1.22.1'

    name: Test with Kubernetes v${{ matrix.kubernetes }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: manusa/actions-setup-minikube@v2.7.2
        name: Setup Minikube
        with:
          minikube version: v1.17.0
          kubernetes version: "v${{ matrix.kubernetes }}"
          github token: "${{ secrets.GITHUB_TOKEN }}"
          driver: docker
          start args: "--addons=registry --addons=ingress"

      - name: Configure Image Pull Secret
        run: |
          kubectl create secret docker-registry github-container-registry \
            --namespace=default \
            --docker-server=ghcr.io \
            --docker-username=${{ secrets.REGISTRY_USERNAME }} \
            --docker-password=${{ secrets.REGISTRY_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "actions@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.4.1

      - name: Install Chart
        run: |
          sleep 30
          kubectl apply -f tests/app/secret.yaml
          helm upgrade --install -f tests/octane/values.yaml octane ./charts/octane
          kubectl get pods

      - name: Install NGINX Ingress Controller
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm upgrade nginx --version=4.0.12 -f tests/octane/nginx.yaml --install ingress-nginx/ingress-nginx

      - name: Update hosts
        run: |
          MINIKUBE_IP=$(minikube ip)
          echo "${MINIKUBE_IP} app.laravel.com" | sudo tee -a /etc/hosts

      - name: Connect to Laravel
        timeout-minutes: 5
        run: |
          until curl --silent -XGET --fail http://app.laravel.com; do printf '.'; sleep 1; done

